#!/usr/bin/env bash
#
# Regenerate the bundled symbolic-icon set embedded in the Veem binary.
#
# Veem draws all its UI icons from an embedded GResource so they look identical
# on every distro/theme (see build.rs + src/main.rs register_resources). Each
# icon is copied out of the system Adwaita theme (or Veem's own custom SVGs) and
# renamed with the "com.getveem.Veem-" prefix, so no host icon theme can
# override it.
#
# Run this after adding/removing an icon reference in the source. It:
#   1. scans src/ for every "com.getveem.Veem-<name>-symbolic" reference,
#   2. re-copies the matching <name>-symbolic.svg from Adwaita / custom sources,
#   3. rewrites resources/veem.gresource.xml to list exactly those files.
#
# Requires: the adwaita-icon-theme package installed (for /usr/share/icons/Adwaita).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
PREFIX="com.getveem.Veem-"
DST="$ROOT/resources/icons/scalable/actions"
CUSTOM="$ROOT/data/icons/hicolor/scalable/actions"   # Veem's own SVGs
ADWAITA="/usr/share/icons/Adwaita"
ADW_LIB="$(ldconfig -p | grep -om1 '/[^ ]*libadwaita[^ ]*\.so[^ ]*' || true)"

# Names actually referenced in the code (strip the prefix back to the base name).
mapfile -t names < <(grep -rhoE '"com\.getveem\.Veem-[a-z0-9-]+-symbolic"' "$ROOT/src" \
    | sed -E 's/^"com\.getveem\.Veem-//; s/"$//' | sort -u)

echo "==> ${#names[@]} icon names referenced in src/"
rm -rf "$DST"
mkdir -p "$DST"

missing=()
for n in "${names[@]}"; do
    out="$DST/$PREFIX$n.svg"
    if   [ -f "$CUSTOM/$n.svg" ]; then
        cp "$CUSTOM/$n.svg" "$out"
    elif f=$(find "$ADWAITA" -name "$n.svg" 2>/dev/null | head -1) && [ -n "$f" ]; then
        cp "$f" "$out"
    elif [ -n "$ADW_LIB" ] && gresource extract "$ADW_LIB" \
            "/org/gnome/Adwaita/icons/scalable/actions/$n.svg" > "$out" 2>/dev/null \
            && [ -s "$out" ]; then
        :  # sourced from libadwaita's internal resources (e.g. adw-external-link)
    else
        rm -f "$out"
        missing+=("$n")
    fi
done

if [ ${#missing[@]} -gt 0 ]; then
    echo "!! Could not source: ${missing[*]}" >&2
    echo "   Add an SVG to $CUSTOM/ and re-run." >&2
    exit 1
fi

# Rewrite the gresource manifest.
{
    echo '<?xml version="1.0" encoding="UTF-8"?>'
    echo '<!-- Auto-generated by tools/gen-icon-gresource.sh — do not edit by hand.'
    echo '     Every symbolic icon Veem draws, prefixed with the app ID so no host'
    echo '     icon theme can override it. Embedded in the binary via build.rs. -->'
    echo '<gresources>'
    echo '  <gresource prefix="/com/getveem/Veem">'
    for f in $(cd "$DST" && ls *.svg | sort); do
        echo "    <file>icons/scalable/actions/$f</file>"
    done
    echo '  </gresource>'
    echo '</gresources>'
} > "$ROOT/resources/veem.gresource.xml"

echo "==> Bundled ${#names[@]} icons; wrote resources/veem.gresource.xml"
